In [3]:
# 必要に応じて
# !pip install --upgrade pip
# !pip install numpy scikit-learn tensorflow matplotlib pillow pandas

In [4]:
# 機械学習のライブラリ関連をインポート
import pandas as pd
import numpy as np

# ランダムにシャッフルして，学習・テストに分割するモジュール
from sklearn.model_selection import ShuffleSplit

# 深層学習のライブラリをインポート
import tensorflow as tf
import tensorflow.keras as keras

#表示系のインポートと設定
%matplotlib inline
import matplotlib.pyplot as plt

# ファイル操作
import os

# 画像操作
from PIL import Image

# 時間取得
import datetime

In [5]:
# DIRS
DATASET_NUM = 1000
DIRS_DATASET = "../Training/Datasets" + str(DATASET_NUM) + "/"

In [6]:
file_names = []
    
# フォルダ内のファイルを取得
files = os.listdir(DIRS_DATASET)

# ファイル名を配列に格納
for file in files:
    file_names.append(file)

# Pythonリスト型をnumpy.ndarray型に変換
file_names = np.array(file_names)


In [7]:
file_names

array(['4510009042127.jpeg', '4510105440272.jpeg', '4510223601998.jpeg',
       '4510332135594.jpeg', '4510355975107.jpeg', '4510400033707.jpeg',
       '4510446196748.jpeg', '4510496688830.jpeg', '4510596087520.jpeg',
       '4510713958379.jpeg', '4511453880061.jpeg', '4511680952412.jpeg',
       '4512085353817.jpeg', '4512128870743.jpeg', '4512192252237.jpeg',
       '4512225800947.jpeg', '4512325886726.jpeg', '4512513823094.jpeg',
       '4512764777649.jpeg', '4512810649972.jpeg', '4512913271405.jpeg',
       '4513028404552.jpeg', '4513030739585.jpeg', '4513182730613.jpeg',
       '4513464598012.jpeg', '4513506880550.jpeg', '4513803667776.jpeg',
       '4513879488534.jpeg', '4513942000905.jpeg', '4514113592964.jpeg',
       '4514524517625.jpeg', '4514585093662.jpeg', '4514729508475.jpeg',
       '4514778219181.jpeg', '4515083435464.jpeg', '4515263593740.jpeg',
       '4515477254151.jpeg', '4515699808857.jpeg', '4515804763729.jpeg',
       '4515874836002.jpeg', '4516003839524.jpeg', 

In [8]:
# # 学習データとテストデータのインデックスを作成
# train_index, test_index = next(ss.split(file_names))

In [9]:
# file_names_train, file_names_test = file_names[train_index], file_names[test_index] # 学習データ，テストデータ

### 画像をnumpy配列にするための関数

In [10]:
def jpeg_to_numpy(image_path):
    # JPEG画像を開く
    image = Image.open(image_path)
    # NumPy配列に変換
    numpy_array = np.array(image)
    
    return numpy_array

def convert_to_grayscale(numpy_array):
    # グレーと言わず2値化
    grayscale_array = np.where(numpy_array <= 128, 0, 255)
    # plt.imshow(grayscale_array) # こいつらのせいで処理が重かった。出力系は要注意
    # print(grayscale_array)
    return grayscale_array


### 画像を配列にしてよしなに

In [11]:
X, y = [], []

In [12]:
for file_name in file_names:
    numpy_array = jpeg_to_numpy(DIRS_DATASET + file_name)
    grayscale_array = convert_to_grayscale(numpy_array)
    for i in range(13):
        X.append(np.where(grayscale_array == 255, i+1, 0))
        y.append(file_name[i])

In [13]:
X = np.array(X)
y = np.array(y, dtype=int)

In [14]:
X

array([[[[ 0,  0,  0],
         [ 1,  1,  1],
         [ 0,  0,  0],
         ...,
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 2,  2,  2],
         [ 0,  0,  0],
         ...,
         [ 2,  2,  2],
         [ 2,  2,  2],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 3,  3,  3],
         [ 0,  0,  0],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 0,  0,  0]]],


       ...,


       [[[ 0,  0,  0],
         [11, 11, 11],
         [ 0,  0,  0],
         ...,
         [11, 11, 11],
         [11, 11, 11],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [12, 12, 12],
         [ 0,  0,  0],
         ...,
         [12, 12, 12],
         [12, 12, 12],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [13, 13, 13],
         [ 0,  0,  0],
         ...,
         [13, 13, 13],
         [13, 13, 13],
         [ 0,  0,  0]]]])

In [15]:
y

array([4, 5, 1, ..., 7, 8, 0])

In [16]:
# ラベルデータをone-hotベクトルに直す
labels = {
    0: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    1: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
    2: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0], 
    3: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 
    4: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0], 
    5: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], 
    6: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], 
    7: [0, 0, 0, 0, 0, 0, 0, 1, 0, 0], 
    8: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], 
    9: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], 
}

y = np.array(list(map(lambda v : labels[v] , y)))

In [17]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 0]])

### データの分割

In [18]:
ss = ShuffleSplit(n_splits=1,      # 分割を1個生成
                  train_size=0.8,  # 学習
                  test_size =0.2,  # テスト
                  random_state=0)  # 乱数種（再現用）

# 学習データとテストデータのインデックスを作成
train_index, test_index = next(ss.split(X))

X_train, X_test = X[train_index], X[test_index] # 学習データ，テストデータ
y_train, y_test = y[train_index], y[test_index] # 学習データのラベル，テストデータのラベル

In [19]:
X

array([[[[ 0,  0,  0],
         [ 1,  1,  1],
         [ 0,  0,  0],
         ...,
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 2,  2,  2],
         [ 0,  0,  0],
         ...,
         [ 2,  2,  2],
         [ 2,  2,  2],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 3,  3,  3],
         [ 0,  0,  0],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 0,  0,  0]]],


       ...,


       [[[ 0,  0,  0],
         [11, 11, 11],
         [ 0,  0,  0],
         ...,
         [11, 11, 11],
         [11, 11, 11],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [12, 12, 12],
         [ 0,  0,  0],
         ...,
         [12, 12, 12],
         [12, 12, 12],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [13, 13, 13],
         [ 0,  0,  0],
         ...,
         [13, 13, 13],
         [13, 13, 13],
         [ 0,  0,  0]]]])

In [20]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [21]:
X_train.shape[0], X_train.shape[1], X_train.shape[2], X_train.shape[3] 

(10400, 1, 112, 3)

In [22]:
X_train

array([[[[ 0,  0,  0],
         [13, 13, 13],
         [ 0,  0,  0],
         ...,
         [13, 13, 13],
         [13, 13, 13],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 3,  3,  3],
         [ 0,  0,  0],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 4,  4,  4],
         [ 0,  0,  0],
         ...,
         [ 4,  4,  4],
         [ 4,  4,  4],
         [ 0,  0,  0]]],


       ...,


       [[[ 0,  0,  0],
         [ 5,  5,  5],
         [ 0,  0,  0],
         ...,
         [ 5,  5,  5],
         [ 5,  5,  5],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [10, 10, 10],
         [ 0,  0,  0],
         ...,
         [10, 10, 10],
         [10, 10, 10],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 3,  3,  3],
         [ 0,  0,  0],
         ...,
         [ 3,  3,  3],
         [ 3,  3,  3],
         [ 0,  0,  0]]]])

### ニューラルネットワークの構築

In [23]:

# 学習し、テストデータで評価し、スコアを表示する
# 引数は、中間層の数、バッチサイズ、epoch数

def fit_epoch(neuron, batch, epochs, ckpt_period):
    ver_name = "1229-v2"
    
    # チェックポイントの設定
    dt_now = datetime.datetime.now()
    checkpoint_path = "./training_ckpt_v" + ver_name + "_d" + str(DATASET_NUM) + "_n" + str(neuron)  + "_b" + str(batch) + "_e" + str(epochs) + "_" + dt_now.strftime('%Y%m%d%H%M%S') + "/cp-{epoch:06d}.ckpt"
    checkpoint_dir = os.path.dirname(checkpoint_path)
    cp_callback = tf.keras.callbacks.ModelCheckpoint(
        checkpoint_path,
        verbose=1,
        save_weights_only=True,
        period=ckpt_period  # 重みをckpt_periodエポックごとに保存します
    )


    # レイヤーのオブジェクトを作成
    Dense = keras.layers.Dense

    # モデルの構造を定義
    model = keras.models.Sequential()
    model.add(tf.keras.layers.Flatten(input_shape=(1, 112, 3)))
    model.add(Dense(neuron, activation='relu'))
    
    # 畳み込み層を追加
    # model.add(tf.keras.layers.Flatten(tf.keras.layers.Conv2D(filters=neuron, kernel_size=(3, 3), activation='relu', input_shape=(1, 112, 3))))

    model.add(Dense(10, activation='softmax')) # 10つのラベルがありsoftmaxで最後の層作る

    # モデルを構築
    model.compile(
        loss='categorical_crossentropy',
        optimizer='Adamax',
        metrics=['accuracy']
    )

    # 必要に応じてチェックポイントから再開
    # model.load_weights("")

    # 学習を実行
    hist = model.fit(X_train, y_train,
        batch_size=batch, # 誤差逆伝播法をするときの1回当たりのデータ数
        epochs=epochs,
        callbacks=[cp_callback],
        verbose=1,
        validation_split=0.1)
    
   # モデルを評価
    score = model.evaluate(X_test, y_test, verbose=1)
    print('正解率=', score[1], 'loss=', score[0])
    
     # 学習の様子をグラフへ描画 
    # 正解率の推移をプロット
    plt.plot(hist.history['accuracy'])
    plt.plot(hist.history['val_accuracy'])
    plt.title('Accuracy')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()

    # ロスの推移をプロット
    plt.plot(hist.history['loss'])
    plt.plot(hist.history['val_loss'])
    plt.title('Loss')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()   

In [24]:
%%time
fit_epoch(16, 512, 400000, 10000)



Epoch 1/400000


19/19 [==============================] - 1s 16ms/step - loss: 5.0818 - accuracy: 0.1018 - val_loss: 2.9213 - val_accuracy: 0.1221
Epoch 2/400000
19/19 [==============================] - 0s 4ms/step - loss: 2.5476 - accuracy: 0.1234 - val_loss: 2.3883 - val_accuracy: 0.1240
Epoch 3/400000
19/19 [==============================] - 0s 3ms/step - loss: 2.3498 - accuracy: 0.1427 - val_loss: 2.3470 - val_accuracy: 0.1308
Epoch 4/400000
19/19 [==============================] - 0s 4ms/step - loss: 2.3279 - accuracy: 0.1505 - val_loss: 2.3344 - val_accuracy: 0.1346
Epoch 5/400000
19/19 [==============================] - 0s 4ms/step - loss: 2.3186 - accuracy: 0.1552 - val_loss: 2.3272 - val_accuracy: 0.1327
Epoch 6/400000
19/19 [==============================] - 0s 4ms/step - loss: 2.3134 - accuracy: 0.1566 - val_loss: 2.3224 - val_accuracy: 0.1337
Epoch 7/400000
19/19 [==============================] - 0s 4ms/step - loss: 2.3091 - accuracy: 0.1585 - val_loss: 2.3192 - val_accu